# API List
# @baseUrl = https://wtgqgtivzc.execute-api.ap-southeast-1.amazonaws.com/dev
@baseUrl = http://localhost:3000/dev


### Create new contact
POST {{baseUrl}}/contact
Content-Type: application/json

{
  "firstName": "Test",
  "lastName": "User",
  "phoneNumber": "60123456610",
  "email": "test@gmail.com",
  "address": "Selangor",
  "birthDate": "19-06-1991"
}

### find contact
GET {{baseUrl}}/contact

{
}


### get all contact
GET {{baseUrl}}/contact

{
}

### Filter contact [sort (-1=descending, 1=acending)]
GET {{baseUrl}}/contact?[$sort][createdAt]=1

{
}

### Get specific contact
GET {{baseUrl}}/contact/61223baa61a88f9a00407358

{
}

### update contact
PATCH {{baseUrl}}/contact?_id=61223baa61a88f9a00407358
Content-Type: application/json

{
  "address": "Cheras, Kuala Lumpur, Malaysia"
}

### remove contact
DELETE {{baseUrl}}/contact?_id=61223baa61a88f9a00407351
Content-Type: application/json

{ 
}
