org: nizamsaidin
app: aws-serverless-api
service: aws-serverless-api
useDotenv: true
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-southeast-1
  lambdaHashingVersion: "20201221"

plugins:
  - serverless-offline

functions:
  main-api:
    handler: handler.handler
    events:
      - http:
          path: /
          method: any
          cors: true
      - http:
          path: /{proxy+}
          method: any
          cors: true
